#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-cloudflare-companion-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-cloudflare-companion ]; then
    echo 'Initialization Complete' > /tmp/state/10-cloudflare-companion
fi

echo ''
echo '** [nginx-proxy-cloudflare-companion] Starting Nginx Proxy Cloudflare Companion'
exec python -u /usr/sbin/cloudflare-companion
