#!/usr/bin/with-contenv bash

### Sanity Test
#if [ -z ${CF_EMAIL} ] ; then printf "** [nginx-proxy-cloudflare-companion] ERROR: CF_EMAIL is not set!\n"; exit 1; fi;
if [ -z ${CF_TOKEN} ] ; then printf "** [nginx-proxy-cloudflare-companion] ERROR: CF_TOKEN is not set!\n"; exit 1; fi;
if [ -z ${TARGET_DOMAIN} ] ; then printf "** [nginx-proxy-cloudflare-companion] ERROR: TARGET_DOMAIN is not set!\n"; exit 1; fi;
if [ -z ${DOMAIN1} ] ; then printf "** [nginx-proxy-cloudflare-companion] ERROR: DOMAIN1 is not set!\n"; exit 1; fi;
if [ -z ${DOMAIN1_ZONE_ID} ] ; then printf "** [nginx-proxy-cloudflare-companion] ERROR: DOMAIN1_ZONE_ID!\n"; exit 1; fi;

### Set Defaults
DEFAULT_TTL=${DEFAULT_TTL:-120}
DOCKER_ENDPOINT=${DOCKET_ENDPOINT:-"unix://var/run/docker.sock"}

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

chmod +x /usr/sbin/cloudflare-companion

mkdir -p /tmp/state
touch /tmp/state/10-cloudflare-companion-init
