#!/usr/bin/with-contenv bash


### Sanity Test
#if [ -z ${CF_EMAIL} ] ; then printf "** [nginx-proxy-cloudflare-companion] ERROR: CF_EMAIL is not set!\n"; exit 1; fi;
if [ -z ${CF_TOKEN} ] ; then printf "** [nginx-proxy-cloudflare-companion] ERROR: CF_TOKEN is not set!\n"; exit 1; fi;
if [ -z ${TARGET_DOMAIN} ] ; then printf "** [nginx-proxy-cloudflare-companion] ERROR: TARGET_DOMAIN is not set!\n"; exit 1; fi;
if [ -z ${DOMAIN1} ] ; then printf "** [nginx-proxy-cloudflare-companion] ERROR: DOMAIN1 is not set!\n"; exit 1; fi;
if [ -z ${DOMAIN1_ZONE_ID} ] ; then printf "** [nginx-proxy-cloudflare-companion] ERROR: DOMAIN1_ZONE_ID!\n"; exit 1; fi;


PROCESS_NAME="nginx-proxy-cloudflare-companion"

### Sanity Test
sanity_var CF_TOKEN "Cloudflare Token"
sanity_var TARGET_DOMAIN "Target Domain"
sanity_var DOMAIN1 "Domain 1"
sanity_var DOMAIN1_ZONE_ID "Domain 1 Zone ID!"


liftoff